### ISSUE TITLE
Question: My own effect vs reusing builtins?

### ISSUE THREAD

**Issue by googleson78** [polysemy-research/polysemy#196]
Sorry in advance if this is not the right place to ask!

In the context of developing an application:

When is it a good (design) choice to define my own effect, albeit it being the same as a built-in one (or perhaps a combination of built-in ones)?

For example:
I want to interact with some service (`X`) for issues which allows for both reading and writing - should I just use `State [Issue]` (`[]` for batch operations) with some `data Issue` or should I write my own `X` effect that is basically `State` but specialized to `[Issue]`?

**Comment by isovector** [comment]
Honestly, I don't have enough experience to have a real answer here. I think I'd suggest spinning up a new effect isomorphic to `State`, and then also provide an interpreter that runs it in terms of `State`. That seems like the best approach to me; it lets you keep your domain logic separate, but also reuse `State` interpretations!

**Comment by jhenahan** [comment]
What @isovector said is exactly what I've been doing. I write the DSL I want to use, then reinterpret it to get the effects I want. This is especially nice because you can limit what parts of the underlying effect your DSL can use. An effect that I wrote the other day is basically State, but with only `get` and `modify`. I could recover `put` with `const`, but then I'm staring at this ugly thing so I know I'm doing a bad thing.

One thing I have found useful, though, is to write your first pass of the business logic using the underlying effects, then use that framework to determine what your own effects should be. For the one I wrote the other day, I wrote the program in terms of State (and some other stuff), recognized that I only needed part of it, and wrote my reinterpretation accordingly.
