### ISSUE TITLE
Please confirm I'm not doing something stupid with callbacks

### ISSUE THREAD

**Issue by newhoggy** [polysemy-research/polysemy#214]
I don't understand what I'm doing, but I managed to get the following code to compile:

```
data Aws m a where
  AwsMkEnv :: Region -> (LogLevel -> LBS.ByteString -> m ()) -> Aws m IO.Env

makeSem ''Aws

runEffAws
    :: Member (Embed IO) r
    => (forall x. Sem r x -> IO x)
    -> Sem (Aws ': r) a
    -> Sem r a
runEffAws lower = interpretH $ \case
  AwsMkEnv region cb -> do
    cb' <- bindT (uncurry cb)
    ins <- getInspectorT
    is  <- getInitialStateT
    env <- embed $ IO.mkEnv region . curry $ \bs -> do
      v <- lower .@ runEffAws $ cb' (bs <$ is)
      pure . fromMaybe () $ inspect ins v
    (env <$ is) <$ getInitialStateT
```

I don't follow what the `bindT`, `getInspectorT`, `lower`, `inspect` and `getInitialStateT` are doing for me.  In particular why the last call to `getInitialStateT` is required to type-check and if I'm even supposed to call it here.

Thanks!

**Comment by newhoggy** [comment]
Yep, that looks heaps more sane.  Thanks so much!

**Comment by alaendle** [comment]
As a polysemy beginner i want to know, if this is the recommended way to handle callbacks?

I'm just asking, because by just looking at older issues and the polysemy implementation its not really clear to me - there exist a few variations (mainly around state handling). So I'm looking for some up-to-date pattern that I could/should adapt - and the example here seems to be the best to me (at least with my limited knowledge).

Thanks in advance for your assistance.

> 
> 
> Give this a go:
> 
> ```haskell
> runEffAws
>     :: Member (Embed IO) r
>     => (forall x. Sem r x -> IO x)
>     -> Sem (Aws ': r) a
>     -> Sem r a
> runEffAws lower = interpretH $ \case
>   AwsMkEnv region cb -> do
>     cb' <- bindT (uncurry cb)
>     is  <- getInitialStateT
>     env <- embed $ IO.mkEnv region . curry $ \bs ->
>       void $ lower .@ runEffAws $ cb' (bs <$ is)
>     pure (env <$ is)
> ```
