### ISSUE TITLE
How to write a declaration for a "Sem r ()" parameter for a function?

### ISSUE THREAD

**Issue by ajkavanagh** [polysemy-research/polysemy#302]
Hi

I spent a few hours last night trying to work out how to write the declaration for a `Sem r ()` function that is passed into a another `Sem r ()` function, and couldn't come up with something that worked.  In the end I gave up and removed the declaration and just let Type Inference "do its thing"(tm).

**Disclaimer**: I'm pretty much a beginner in Haskell, and deciphering the (long) error messages is not my forte, but I think what is going on is around deducing the 'r' bit, and it being two general.  But that probably doesn't make any sense.

Anyway, here are the three functions.

Firstly the top level caller:

```haskell
run :: [Int] -> IO (Either MachineException ())
run opcodes = runWith opcodes exec
```

Now the `exec` function:

```haskell
exec :: Members '[ State Machine
                 , Error MachineException
                 , CP.Log String
                 , Teletype
                 ] r
        => Sem r ()
exec = do
...
```

And finally the function that I can't work out what to write in the declaration:

```haskell
runWith :: Members '[ State Machine
                     , Teletype
                     , Error MachineException
                     ] r
        => [Int]
        -> Sem r ()    -- runner param
        -> IO (Either MachineException ())
-- I can't work out what type description to put in for 'runner' -- it ends up
-- with really hard types -- so we'll leave it up to polysemy.plugin and GHC to
-- infer the types  -- the above breaks it; commented out it works.
runWith opcodes runner =
    runner
        & evalState (loadMachine opcodes)      -- [Teletype, Log String, Embed IO, Error MachineException]
        & CP.runLogAction @IO logStringStdout  -- [Teletype, Embed IO, Error MachineException]
        & teletypeToIO                         -- [Embed IO, Error MachineException]
        & errorToIOFinal @MachineException     -- [Embed IO]
        & embedToFinal @IO
        & runFinal
```

What you see in the commented out header is the last in a long line of things that I tried, but I couldn't come up with a type declaration for `runner`.  The error with:

```
/home/alex/Projects/Programming/Haskell/aoc2019/src/OpCodeMachine.hs:313:11: error:
    • Could not deduce: r
                        ~ '[State Machine, CP.Log String, Teletype, Error MachineException,
                            Polysemy.Embed.Type.Embed IO, Polysemy.Final.Final IO]
      from the context: Members
                          '[State Machine, Teletype, Error MachineException] r
        bound by the type signature for:
                   runWith :: forall (r :: [(* -> *) -> * -> *]).
                              Members '[State Machine, Teletype, Error MachineException] r =>
                              [Int] -> Sem r () -> IO (Either MachineException ())
        at src/OpCodeMachine.hs:(301,1)-(307,42)
      ‘r’ is a rigid type variable bound by
        the type signature for:
          runWith :: forall (r :: [(* -> *) -> * -> *]).
                     Members '[State Machine, Teletype, Error MachineException] r =>
                     [Int] -> Sem r () -> IO (Either MachineException ())
        at src/OpCodeMachine.hs:(301,1)-(307,42)
      Expected type: Sem r ()
                     -> Sem
                          '[CP.Log String, Teletype, Error MachineException,
                            Polysemy.Embed.Type.Embed IO, Polysemy.Final.Final IO]
                          ()
        Actual type: Sem
                       '[State Machine, CP.Log String, Teletype, Error MachineException,
                         Polysemy.Embed.Type.Embed IO, Polysemy.Final.Final IO]
                       ()
                     -> Sem
                          '[CP.Log String, Teletype, Error MachineException,
                            Polysemy.Embed.Type.Embed IO, Polysemy.Final.Final IO]
                          ()
    • In the second argument of ‘(&)’, namely
        ‘evalState (loadMachine opcodes)’
      In the first argument of ‘(&)’, namely
        ‘runner & evalState (loadMachine opcodes)’
      In the first argument of ‘(&)’, namely
        ‘runner & evalState (loadMachine opcodes)
           & CP.runLogAction @IO logStringStdout’
    • Relevant bindings include
        runner :: Sem r () (bound at src/OpCodeMachine.hs:311:17)
        runWith :: [Int] -> Sem r () -> IO (Either MachineException ())
          (bound at src/OpCodeMachine.hs:311:1)
    |
313 |         & evalState (loadMachine opcodes)      -- [Teletype, Log String, Embed IO, Error MachineE
xception]
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

So I guess I'm curious about what *should* go in instead of `Sem r ()` or variations on that theme?

**Comment by KingoftheHomeless** [comment]
The issue lies in the type definition with `runWith`:
```haskell
runWith :: Members '[ State Machine
                     , Teletype
                     , Error MachineException
                     ] r
        => [Int]
        -> Sem r ()    -- runner param
        -> IO (Either MachineException ())
```
Because this is polymorphic over `r`, this basically says that given _any_ `Sem r` such that `r` has
 `State Machine`, `Teletype`, and `Error MachineException`, `runWith` will run it to `IO`. But you can't actually guarantee that, since `r` could contain effects you can't process, or the ordering of the effects that you demand is in it may not necessarily be in the order you want! 

Having a function that takes a `Sem r` argument and runs it to the final monad isn't a very common pattern (as opposed to having the `Sem r` computation be hardcoded and then process it, like in the examples in the `README.md`), which is why this doesn't typically crop up.

There are two ways to address this. You can specify the exact effect stack that `runWith` processes, like this:
```haskell
runWith :: [Int]
        -> Sem '[
            State Machine
          , CP.Log String
          , Teletype
          , Error MachineException
          , Embed IO
          , Final IO] ()    -- runner param
        -> IO (Either MachineException ())
```
This is the inferred type of `runWith`. Problem is that it's pretty verbose, since you need to specify the intermediate effects, so another way is to leverage `RankNTypes`, like this:
```haskell
runWith :: [Int]
        -> ( forall r
            . Members '[
                  State Machine
                , Teletype
                , Error MachineException
                ] r
           => Sem r ()
            )    -- runner param
        -> IO (Either MachineException ())
```
The difference between this and your original definition of  `runWith` is that this version, rather than saying "I will handle any `Sem r` that contains `State Machine`, `Teletype`, and `Error MachineException`", this says "I will handle any `Sem r` computation that is _polymorphic_ over `r`, such that the computation will work with any effect stack `r`, as long as that `r` contains `State Machine`, `Teletype`, and `Error MachineException`". Basically, you move the responsibility of being generic from `runWith` to the `runner` argument. `runWith` will then be able to instantiate the runner to the concrete
```haskell
Sem '[
    State Machine
  , CP.Log String
  , Teletype
  , Error MachineException
  , Embed IO
  , Final IO] ()
```
and then handle it. The problem with this solution is that the use of the higher-ranked type may trip up type inference, and it may not optimize as well.

**Comment by KingoftheHomeless** [comment]
A note: the reason this is a problem is only because you're taking the provided `Sem r` and immediately processing it to the final monad. You can easily write declarations for functions that take `Sem r` arguments and work with it, as long as you don't change `r` -- like all the higher-order actions such as `listen`, `censor`, `catch`, etc -- or as long as you are processing concrete elements in the beginning of the list -- such as `runInputSem`.

**Comment by ajkavanagh** [comment]
Thank you very much for the extended explanation.  I *think* I might be beginning to grasp what is going on.  I don't really understand `RankNTypes` types fully, but I do see what you've done there to specify the type.  I guess I'm at the level of "I'm happy to understand (more or less!) how to use Polysemy", but definitely not at the "I know Polysemy works"!  I'll keep plugging away.

I think, however, I agree with your comment:

> Having a function that takes a Sem r argument and runs it to the final monad isn't a very common pattern (as opposed to having the Sem r computation be hardcoded and then process it, like in the examples in the README.md), which is why this doesn't typically crop up.

I certainly couldn't find any *other* code like it.  I'm going to do away with that pattern (passing a `Sem r` argument).

Thanks again!

**Comment by KingoftheHomeless** [comment]
To reempathize, it's specifically the pattern of taking a `Sem r` argument and then _immediately running it to the final monad_ that is the problem. In other contexts, you can pass `Sem r` arguments fine.
