### ISSUE TITLE
Output to lazy list

### ISSUE THREAD

**Issue by Caagr98** [polysemy-research/polysemy#310]
Take the program `mapM_ output [1..]`. It will of course simply output an infinite list of integers, but accessing this list has proven difficult. Running it with `runOutputList` doesn't work, since that uses `reverse` internally. `runOutputSem (embed . print)` works for printing it, but that's not generalizable. Is there any way to do this?

**Comment by googleson78** [comment]
Lazy `Writer` doesn't suffer from this:
```haskell
> import qualified Control.Monad.Writer as W
> take 10 $ snd $ W.runWriter $ mapM_ (W.tell . (:[])) [0..]
[0,1,2,3,4,5,6,7,8,9]
```
Strict one does:
```haskell
> import qualified Control.Monad.Writer.Strict as W
> take 10 $ snd $ W.runWriter $ mapM_ (W.tell . (:[])) [0..]
^CInterrupted.
```
Lazy state suffers from this too:
```haskell
> import qualified Control.Monad.State.Lazy as State
> take 10 $ snd $ (`State.runState` []) $ mapM_ (State.modify . (\x -> (++ [x]))) [0..]
^CInterrupted.
> take 10 $ snd $ (`State.runState` []) $ mapM_ (State.modify . (\x -> ([x] ++))) [0..]
^CInterrupted.
```


So the issue will still persist even if the `reverse` is removed, because we use `Polysemy.State.runState` to interpret `Polysemy.Output.runOutputList`, and it uses `StateT` internally. Using `Polysemy.State.runLazyState` will not help either.

It is also worth noting that although the lazy `Writer` does fine, it does have other issues (space leaks - [\[1\]](https://mail.haskell.org/pipermail/libraries/2013-March/019528.html), [\[2\]](https://blog.infinitenegativeutility.com/2016/7/writer-monads-and-space-leaks))

**Comment by KingoftheHomeless** [comment]
I suppose we could use `runOutputMonoidLazy` and `runWriterLazy` using `Control.Monad.Writer.Lazy` as the carrier. I don't know how widely used it would be, but it's worth existing.
I'll cook it up.

**Comment by googleson78** [comment]
I haven't read through all the `Writer` issues, so I don't know if this is fundamentally impossible, but it would be interesting if we could have a lazy `Output` that **doesn't** space leak.

**Comment by KingoftheHomeless** [comment]
It's probably fundamentally impossible. `Writer`'s space issue is that its `Monad` instance is as follows:
```haskell
m >>= f = WriterT $ do
  ~(a, s1) <- runWriterT m
  ~(b, s2) <- runWriterT (f a)
  return (b, s1 <> s2)
```
The problem is that final `return`. You can't apply tail-call optimization: you need to save the context in order to then run `s1 <> s2`, which means each use of `>>=` adds a thunk to the stack. This quickly grows out of control. The solution to this is CPS (which the `StateT` solution is) but a classic problem of CPS is that it can't be used lazily, since the entire result is returned all at once by the final computation.
