### ISSUE TITLE
Update hackage metadata

### ISSUE THREAD

**Issue by Uroc327** [polysemy-research/polysemy#331]
The metadata on hackage seems wrong to me. It is stated that `polysemy-1.3.0.0` requires `first-class-families < 0.9` whereas the project's `polysemy.cabal` file requries `first-class-families < 0.8` still. The update to fcf 0.8 was made after version 1.3.0.0.

This breaks for example automatic generation of packages for distributions, that take dependency requirements from hackage but build using the cabal file. They first install `first-class-families-0.8` but then the cabal file requires a version below 0.8.

**Comment by googleson78** [comment]
The dependency on Hackage was updated in a hackage revision - http://hackage.haskell.org/package/polysemy-1.3.0.0/revisions/

The `polysemy.cabal` file in current master (016c16fbb1b57a0d728e57e2cf8e36453e8edd8d) [requires `< 0.9`](https://github.com/polysemy-research/polysemy/blob/016c16fbb1b57a0d728e57e2cf8e36453e8edd8d/polysemy.cabal#L99)

I'm not sure I understand where the issue is.

If someone is using the [revisionless archive](http://hackage.haskell.org/package/polysemy-1.3.0.0/src/) directly from Hackage, where the `.cabal` is outdated, then that means they should become revision-aware? (if this is the issue at hand)

**Comment by Uroc327** [comment]
Hmm. I'm really not sure. I stumbled upon this when trying to use [gentoo-haskell/hackport](github.com/gentoo-haskell/hackport) to install/merge polysemy.
