### ISSUE TITLE
`traceToIO` with `stderr`?

### ISSUE THREAD

**Issue by Anrock** [polysemy-research/polysemy#408]
Intended use of `Trace` is for logging but it's main interpreter `traceToIO` is hardcoded to output to `stdout` while more common place to put error/diagnostics/logs for unix programs is `stderr`. 

Not sure what's the right action here but, imo, in ideal world `traceToIO` should output to `stderr` by default.

**Comment by tek** [comment]
sounds reasonable to me. any idea if there was intention behind this?

**Comment by KingoftheHomeless** [comment]
To my knowledge, Sandy just made it that way. For reference, both `in-other-words` and `fused-effects` use `stderr`, while `freer-simple` uses `stdout`. As you might've guessed, I prefer `stderr`.

**Comment by Anrock** [comment]
@KingoftheHomeless What about backwards compatibility? Just change `stdout` to `stderr` and we're good or more elaborate strategy is needed?

**Comment by KingoftheHomeless** [comment]
The only concern is if people use `Trace` in order to write command line programs, which is _sort of_ a valid concern, but it's not what `Trace` is meant for to begin with. Beyond that, although it's certainly a breaking change, I doubt that it's a particularly breaking one. People using `Trace` for logging to a file are more likely to write their own `Trace` interpreter which writes to a file handle rather than _piping the program_.

My opinion: just make the change, modify the documentation accordingly, and list it as a (currently unreleased) breaking change in CHANGELOG.

**Comment by tek** [comment]
I would find it most sensible to provide `traceToStdout` and `traceToStderr`

**Comment by googleson78** [comment]
And wrt backwards compat we can have a deprecated annotation on `traceToIO`, while making it a synonym for `tracetoStdout`

**Comment by tek** [comment]
sounds very reasonable

**Comment by KingoftheHomeless** [comment]
I agree with both of your suggestions.

**Comment by tek** [comment]
implemented!

**Comment by Anrock** [comment]
Ah, that was fast :D
