### ISSUE TITLE
Is it possible to define interpreter functions using polysemy's error?

### ISSUE THREAD

**Issue by qwbarch** [polysemy-research/polysemy#472]
If I had an effect such as this:
```haskell
data UserService m a where
  InsertUser :: User -> UserService m (Either UserError ())
```

Is it possible to replace ``Either`` with a polysemy error? I can't get this to typecheck:
```haskell
data UserService m a where
  InsertUser :: Member (Error UserError) m => User -> UserService m ()
```

**Comment by googleson78** [comment]
I'm not sure what exactly your desired outcome is, but usually you put this constraint at interpreter site of `insertUser`:

```haskell
interpretUserService :: Member (Error UserError) r => ... -> Sem r ()
interpretUserService = interpret \case
  InsertUser -> do
  ...
  case operationReturningEither of 
    Left x -> throw x
    Right x -> ...
```

**Comment by qwbarch** [comment]
The reason why I wanted to have it on the function itself is to have it handled at the call-site rather than where the ``Sem`` effects are interpreted.  
I guess I'll have to stick to ``Either`` in this case then. Thanks for the answer!

**Comment by googleson78** [comment]
If you want to have it handled at the call site, I think you might be able to use the `Exceptional` or `Scoped` stuff for that. cc @tek @KingoftheHomeless

**Comment by KingoftheHomeless** [comment]
Yup! What you're looking for is [`Resumable`](https://hackage.haskell.org/package/polysemy-resume-0.7.0.0/docs/Polysemy-Resume.html#t:Resumable)! I prefer to call it `Exceptional`, but @tek prefers `Resumable` and since they're the author of `polysemy-resume` that's what it's called. With the groundbreaking work we're currently doing with `Scoped` (an effect we've recently discovered can be made to subsume `Resumable`, and an effect we're still finding more and more discoveries about), we're gonna bring `Resumable` into Polysemy proper, and then I ca _hopefully_ convince Torsten to let me call it `Exceptional`.

**Comment by qwbarch** [comment]
Oh cool I'll try out ``Resumable``. Thank you for the pointers!
