### ISSUE TITLE
Lifting within `Final`

### ISSUE THREAD

**Issue by drlkf** [polysemy-research/polysemy#479]
I have a monad `m` with a `MonadIO` instance, which I'm using as the `Final` monad in my effects. I also have some functions defined with `Member (Final IO)`, which I would like to invoke within the `Final m` `Sem`. I don't quite understand what I'm supposed to do. `finalToFinal` seems to be the most obvious but I have two problems:
1. I only have a natural transformation from `IO` to `m` in `liftIO` (`unliftio` is out of the question since `m` also has `MonadState`)
2. `finalToFinal` requires `Member (Final m2)` as well as `Final m1 ': r` for the input monad, which is not quite what I want, I want to transform the `Final` monad, not consume one of two

I also tried to look at `Tactics` and `Strategy` but I have to admit it's not quite clear to me what they do. Some example usage of those features would be welcome in the documentation IMO, I'm having trouble understanding the benefits with the `Resource` example.

Any help appreciated!

**Comment by KingoftheHomeless** [comment]
`Final` is a rather restrictive effect to interpret, but interpretation of it is slightly more permissive than `finalToFinal` would suggest -- if your final monad is `MonadBaseControl IO m`, you can implement an effect transformer from `Final IO` to `Final m`: [see this comment for an implementation](#https://github.com/polysemy-research/polysemy/issues/323#issuecomment-591438566). This function is not provided anywhere -- not in polysemy proper because it incurs a `monad-control` dependency, and not in `polysemy-zoo` because... I forgot, I genuinely thought it was in that library.
Note that if you can create an instance of `MonadBaseControl` for your final monad, and the only thing preventing you is that it would be an orphan instance, then you can create a newtype wrapper, use `finalToFinalBaseControl` to transform `Finak IO  to `Final (YourNewtype m)`, and then use `finalToFinal` to transform the `Final (YourNewtype m)` to `Final m`. If you can't get access to even `MonadBaseControl IO m`, or equivalent or greater power, there's nothing you can do. If all you have access to is a natural transformation from `IO` to `m`, then you can only make use of `Embed IO`, and transform that to `Embed m` via `runEmbedded`, and then transform `Embed m` to `Final m` via `embedToFinal`. That is indeed why `Embed` still exists and is separate from `Final`.

I don't understand what you're trying to say with 2., which probably implies you've misunderstood something about how effect systems work with regards to the effect stack and how you do interpretation. `finalToFinal` _is_ a transformative interpreter, in that it translates usages of an effect `Final m` to usages of the effect `Final n`. Lets call your final monad `M`, and let's say that you want to leverage something using `Final IO`, e.g. `errorToIOFinal`. If you are able to use `finalToFinal` or `finalToFinalBaseControl`, and say that you could leverage `finalToFinal`, then your final interpretation stack could look something like this:
```haskell
program :: M (Either String ())
program =
    runFinal @M
  . embedToFinal @M
  . finalToFinal ioToM mToIO -- Interprets all usages of 'Final IO' by translating them to 'Final M'
  . errorToIOFinal @String
  $ app
```
As long as `app` is defined with a polymorphic effect stack, bounded only by membership constraints on the effect stack, like so:
```
app
  :: ( Member (Error String) r
     , ... -- other membership constraints on r
     )
  => Sem r ()
app = ...
```
Then doing an interpretation stack like the above Just Works. The fact that you're talking about "consuming one of two" implies you have at least partially a concrete effect stack for `app`, which is typically not what you want to do -- but if you really do want to do it, you can write a reinterpretative rather than transforming variant of `finalToFinal` by leveraging `raiseUnder` as follows:
```
finalIntoFinal :: forall m1 m2 r a
                . (forall x. m1 x -> m2 x)
               -> (forall x. m2 x -> m1 x)
               -> Sem (Final m1 ': r) a
               -> Sem (Final m2 ': r) a
finalIntoFinal to from = finalToFinal to from . raiseUnder
```

**Comment by KingoftheHomeless** [comment]
A final note -- documentation on `Tactics` and `Strategy` -- yeah, it sucks, but more than that, those two interfaces also suck. We've been working on a massive rewrite of `polysemy` that will replace `Tactics` and `Strategy` with an entirely new, more user-friendly interface, and so we won't be spending any effort on documenting `Tactics` and `Strategy` beyond the scattered material that already exists -- it will instead go to the new interfaces. Progress on the library rewrite has been slow -- by this point it has lasted multiple years, and most of time we've been mostly inactive on it. However, we have rekindled development recently and ramped it up massively. By this point, we're actually almost done -- we have actually developed a completely implemented draft of the rewrite, but which has been revised multiple times for optimization, and also integrating continuous discoveries on how to further improve the library. We're currently working on what is planned to be the last or next-to-last revision. Still no concrete promises when polysemy v2 will be delivered proper, but I can _pretty_ confidently say it will happen before the end of the year.

**Comment by drlkf** [comment]
Thank you for all this information. Regarding my point about consuming one of the effects, from what I understand, if we look at the type signature for `finalToFinal`:
```haskell
finalToFinal :: forall m1 m2 r a
              . Member (Final m2) r
             => (forall x. m1 x -> m2 x)
             -> (forall x. m2 x -> m1 x)
             -> Sem (Final m1 ': r) a
             -> Sem r a
```

Since `r` has `Member (Final m2)`, we can consider `r` as `Final m2 ': r'`, which
turns the signature into:

```haskell
finalToFinal :: ()
             => (forall x. m1 x -> m2 x)
             -> (forall x. m2 x -> m1 x)
             -> Sem (Final m1 ': Final m2 ': r')) a
             -> Sem (Final m2 ': r') a
```

Unless I've misunderstood this constraint?

**Comment by drlkf** [comment]
All of that makes sense yes. Maybe I'd like to go back to my question and
rephrase it slightly since I feel we've strayed a bit from the original topic:

Is there a way, given `Member (Final IO) r1`, `Member (Final m) r2` and
`MonadIO m`, to do something like:

```haskell
liftFinalIO :: ()
  => MonadIO m
  => Member (Final IO) r1
  => Member (Final m) r2
  => Sem r1
  -> Sem r2
liftFinalIO = something . liftIO
```

I feel like the `MonadBaseControl IO` solution is somehow overkill since I
"just" want to lift the `Final` effect in the same way I would lift a single
monad.

**Comment by tek** [comment]
are you certain you need `Final` for `IO`?

**Comment by drlkf** [comment]
I had to switch from `Embed` due to [this](https://github.com/polysemy-research/polysemy/issues/477) but I'm not quite sure it was a good idea to switch the whole codebase but I've had issues really understanding the difference between `Final` and `Embed` clearly tbqh. Maybe I should revert to using `Embed` and use `embedToFinal` only in the code affected by the previous issue and that would allow me to use `runEmbedded liftIO` ?

**Comment by tek** [comment]
ah, right. have you tried using your special `Final m` instead of `IO` in your `runStreamingCommand`?

I don't think you'll be successful with `Embed` in that scenario.

**Comment by tek** [comment]
another possible approach could be to convert your special monad into `Sem` – if it's just a `ReaderT IO` or something, you can interpret it as `Polysemy.Reader`.

**Comment by drlkf** [comment]
>ah, right. have you tried using your special `Final m` instead of `IO` in your `runStreamingCommand`?

The problem is that I have two programs using those functions, one of which runs directly in `IO` and the other in `m`; maybe there is a way to make it uniform by putting `Final m` everywhere and using another interpreter? I'd like to avoid having to use `liftIO` everywhere though, if that's possible.

**Comment by tek** [comment]
I'd suggest you abstract `runStreamingCommand` with an effect, and in its interpreter, use `MonadBaseControl IO m => Member (Final m) =>`.
Then run it late in the stack as `interpretStreamingCommand @YourFinalMonad`.

**Comment by drlkf** [comment]
So that means switching all the existing code from `Final IO` to `Final m`, correct ?

**Comment by drlkf** [comment]
I do not, unfortunately. I ended up making a separate thread handling effects and communicating events through simple `IO` bounded channels. I suppose the idea of lifting in the traditional sense is a bit more complicated than I anticipated when using `Embed` and `Final`.
